### ISSUE TITLE
Motion component finding inifinite mass

### ISSUE THREAD

**Issue by Vinceistdoof** [Deepercreeper/Magix#13]
## For the game there will be no collisions between entities with infinite mass. Thus the accelerated Box of an entity with infinite Mass and velocity 0 should be only the object itself.

If these conditions are not met, there could be a real mess when entitys build a bridge between a moving platform with infinite mass and the ground. In this case the whole ground would be considered to be a motion component.

**Comment by Deepercreeper** [comment]
The max velocity for a single entity is computed via the following formula:

``` java
if (Double.isFinite(entity.getMass())){
    return momentum.times(2 / entity.getMass()).plus(velocity);
}
return entity.getVelocity();
```

So if the entity mass is finite, the default computation of the max velocity is applied and for infinite entities the velocity box will be the containment of the velocity apllied position and the current position of the entity, which is pretty accurate.
